# Site settings
baseurl = "https://greatminds-life.github.io/verse/"
languageCode = "en-us"
title = "50 Verses"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "docs"

[params]
    # Meta
    title = "50 VERSES"
    subtitle = ""
    author = "PPC"
    description = "50 Bible verses to memorize"
    keywords = "Bible,Church,words,God,Jesus,Life,Cross,Reborn,Resurrection"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Get the theme"

    # Footer text
    footertext = "Prepared by [Praise Presbyterian Church 찬양교회](https://www.chanyang.org/)"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
